### ISSUE TITLE
Contribute some convergence diagnostic tools

### ISSUE THREAD

**Issue by roualdes** [StanJulia/StanSample.jl#37]
Too long ago now, [we spoke on Julia's Discourse channel](https://discourse.julialang.org/t/adding-a-build-step-for-cmdstan-inside-a-julia-package/51844/16), where I offered up Julia versions for many of the [CmdStan tools](https://mc-stan.org/docs/2_25/cmdstan-guide/cmdstan-tools.html#cmdstan-tools).

You can find my code [here](https://github.com/roualdes/yastan/blob/master/convergence.jl).  I'm happy to help contribute these to the StanSample package, if you are still interested.  

As I see it, agreement on the API, which I admittedly did not spend much time thinking about, and formal testing could be some good first steps.  

I'm happy to help add these tools, even if the beginning of the semester has set me back a bit. 
Let me know how you'd prefer we proceed, logistically.  For instance, just thinking out loud, I'd appreciate it if you would set up a branch with some simple tests that I could expand on.  I could work on fork, after you help get me started.  Or, whatever you think is best.

**Comment by goedman** [comment]
Hi Edward,

Absolutely, I'll send you an invite to the StanJulia set of repositories so you can create a branch (or I could do it for you).

Just let me know what will help you get going. Probably the easiest way to start is take a couple of the slightly more complicated models and connect the functions in your code base so we can almost directly compare between your code and calling `stan_summary(model, true)`.

Does that make sense?

**Comment by roualdes** [comment]
Yes, that makes sense.  I've looked through some of the tests you've got already, and it all looks pretty self-explanatory.  Now I just need to find the time to get to this.  Thanks in advance for your patience.

**Comment by goedman** [comment]
I think I close this issue for now. There is a new package, MCMCDiagnosticTools.jl that might help here. Thanks for your interest.
