### ISSUE TITLE
Simplify API for seed

### ISSUE THREAD

**Issue by itsdfish** [StanJulia/StanSample.jl#45]
Hi Rob,

I was wondering whether it would be possible to simplify the API for setting a random seed. Currently, it requires

```
SampleModel(
  ...;
  seed = StanSample.StanBase.RandomSeed(seed),
  ...
)
```
I'm there are a few alternatives depending on the reason the seed is wrapped in `RandomSeed`. If `RandomSeed` is not necessary, it would be treated as an integer with a default value. Alternatively, we could set a default keyword value in the constructor and wrap that integer in `RandomSeed` inside the constructor.  Would you be amenable to that?

It seems like a similar approach could be used for the other keywords, but seed might benefit the most from a simpler API.

**Comment by itsdfish** [comment]
You also noted in a previous [issue](https://github.com/StanJulia/CmdStan.jl/issues/119) that `n_chains::Vector{Int}` could be changed to `n_chains::Int`. I could help with any of these changes if it is not too involved.

**Comment by goedman** [comment]
Very interesting question! I (forever and ever!) kind of parsed the Stan Language structure but likely it is time to review that.
I'll do a copy of tests. Like your chains question, not sure if we can update the SampleModel fields directly, but I'll try it.

**Comment by goedman** [comment]
So I wonder if we should all make them keyword arguments with defaults. I think that would be a significant improvement:
```
sm = SampleModel("m4_1s", stan4_1; seed=-1, nsamples=1000, delta=0.85, nchains=4, ...)
```

**Comment by goedman** [comment]
I'll have a look over the next couple of days what such a change entails.

This is code that that has been around  for 10 years so I want to be careful. It also relates to my remark [here](https://github.com/StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl/issues/9#issuecomment-939351490).

In your example above, is your objection agains the use of `RandomSeed()` or the fact that RandomSeed is not exported and you have to use `StanSample.StanBase.RandomSeed(seed)`? Just wondering if this is a possible quick fix until the bigger update becomes available. Or, as you suggest, make the type a union and deal with it in the SampleModel call.

**Comment by goedman** [comment]
Hi Chris, just pushed StanSample.jl v4.3.0 which allows kwargs `seed` and `n_chains`, e.g.
```
rc = stan_sample(model; data, seed=123, n_chains=5)
```

**Comment by itsdfish** [comment]
Hi Rob,

These changes look good!

To answer your questions above, I usually run 4 chains and set a seed to make it reproducible. If I am doing a parameter recovery simulation to validate the model, I  generate simulated data in Julia and set the same seed in julia via `Random.seed!`. From what I can tell, it is sufficient to reproduce the posterior samples by passing a single seed value (I cannot think of a case where one would need to specify the seed of each chain).   I typically do not save warmup samples, unless I need them to diagnose a model that is not converging.  So I'm not sure whether it is worth your trouble. 


Now that I understand your design better, it seems like you could destructure `Sample` into keyword arguments for `SampleModel` as I originally proposed. This would greatly simplify the API, much like changing `seed` to an integer keyword. There are different ways to use dispatch if you need to accommodate a new sample in the future. For example, you could do something like this:

```
abstract type SampleModel end

struct NUTSModel <: SampleModel
...
end

struct NewModel <: SampleModel
...
end

function stan_sample(stan_model::SampleModel; kwargs...)
...
end
```
This would allow you the flexibility to add new samplers and also destructure the fields of `Sample` into keywords for a simpler API. So I think I was incorrect earlier when I thought there was a tradeoff between dispatch and simplifying the API.

**Comment by itsdfish** [comment]
Awesome! I look forward to the next version.

**Comment by itsdfish** [comment]
I just upgraded. Very nice!
