### ISSUE TITLE
Error when compiling SampleModel

### ISSUE THREAD

**Issue by jfb-h** [StanJulia/StanSample.jl#47]
Hi,

I just installed cmstan on a Windows 10 machine via conda, as recommended in the [cmdstan user guide](https://mc-stan.org/docs/2_28/cmdstan-guide/cmdstan-installation.html). The cmdstan home directory is then `C:\Users\Jakob\Anaconda3\Library\bin\cmdstan`, from which I were able to succesfully run the [cmdstan examples](https://mc-stan.org/docs/2_28/cmdstan-guide/cmdstan-installation.html#checking-the-stan-compiler).

However, I can't get the example in `StanSample.jl` to work:

```julia

ENV["JULIA_CMDSTAN_HOME"] = "C:\\Users\\Jakob\\Anaconda3\\Library\\bin\\cmdstan"

using StanSample

model = "
	data { 
	  int<lower=0> N; 
	  int<lower=0,upper=1> y[N];
	} 
	parameters {
	  real<lower=0,upper=1> theta;
	} 
	model {
	  theta ~ beta(1,1);
	    y ~ bernoulli(theta);
	}
";

sm = SampleModel("bernoulli", model, tempdir())
```

This results in the following Error:

```
Error when compiling SampleModel bernoulli:
/usr/bin/expr: missing operand
Try '/usr/bin/expr --help' for more information.
/usr/bin/rm: missing operand
Try '/usr/bin/rm --help' for more information.
make: *** [make/program:60: C:\Users\Jakob\AppData\Local\Temp\bernoulli.exe] Error 1
```

I am on julia 1.7.

Am I missing something or is this a bug?

**Comment by goedman** [comment]
Hi @jfb-h ,

I'm not sure if this is bug or just a different setup of CmdStan. I am a bit concerned that the docs explicitly state that  "The conda installation is designed so one can use the R or Python bindings to CmdStan seamlessly". 

To figure this out can you let me know what binaries are in "C:\\Users\\Jakob\\Anaconda3\\Library\\bin\\cmdstan\\bin"?

There should be something like diagnose, stanc, print and stan summary.

Also, can you try above test program with:
```
sm = SampleModel("bernoulli", model, mktempdir())
```

Rob

**Comment by jfb-h** [comment]
Hi Rob, 

thanks for the quick reply!

These are the contents of `C:\Users\Jakob\Anaconda3\Library\bin\cmdstan\bin`:

![grafik](https://user-images.githubusercontent.com/61913033/144434482-42bd5d8d-402d-433f-89e9-f3509559dd06.png)

Testing with 

```julia
sm = SampleModel("bernoulli", model, mktempdir())
```

yielded the same error.

Best,
Jakob

**Comment by goedman** [comment]
This occurs inside of `make`. 

Line 60  (if that is what the 60 in "make: *** [make/program:60: C:\Users\Jakob\AppData\Local\Temp\bernoulli.exe] Error 1" refers to) in make:
```
ifneq (,$(findstring g++,$(CXX)))
  CXX_TYPE ?= gcc
endif
```
it tries to call `/usr/bin/expr`?

I'll post a (quick ?) question on the Stan forum.

**Comment by jfb-h** [comment]
Thanks!

**Comment by goedman** [comment]
By the way, did you do:
```
One can create a new conda environment (named stan-env) and install CmdStan with the following command.

conda create -n stan-env -c conda-forge cmdstan
or install it in an existing environment with

conda install -c conda-forge cmdstan
The conda installation is designed so one can use the R or Python bindings to CmdStan seamlessly. Additionally, it provides the command cmdstan_model to activate the CmdStan makefile from anywhere. To enable either of these, ensure your environment is activated1 with conda activate <env>, where <env> is the name of the environment CmdStan was installed into. In the first command above, the environment was named stan-env, but any name may be used so long as you are consistent.

You can check which version of CmdStan is installed in your current environment by running the following command.

conda list cmdstan
```

and what comes out of the last command?

**Comment by jfb-h** [comment]
I just installed cmdstan into the base conda environment. `conda list cmdstan`  returns

```
(base) PS C:\Users\Jakob> conda list cmdstan
# packages in environment at C:\Users\Jakob\Anaconda3:
#
# Name                    Version                   Build  Channel
cmdstan                   2.28.2               hc4b6281_0    conda-forge
```

**Comment by goedman** [comment]
Getting a few helpful hints [here](https://discourse.mc-stan.org/t/installing-cmdstan-using-conda/25536/5).

Will experiment a bit more.

**Comment by jfb-h** [comment]
In case it helps, here's the g++ and mingw32-make versions which seem to have been installed through the conda installation:

```
(base) PS C:\Users\Jakob> g++ --version
g++.exe (Rev5, Built by MSYS2 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
(base) PS C:\Users\Jakob> mingw32-make --version
GNU Make 4.1.90
Built for Windows32
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
(base) PS C:\Users\Jakob>
```

**Comment by goedman** [comment]
So using Conda.jl and `import Conda;Conda.add("cmdstan", :stan_dev)` I found the cmdstan directory in
```
julia> using StanSample
julia> import Conda

julia> Conda.add("cmdstan", :stan_dev)
[ Info: Running `conda install -y cmdstan` in stan_dev environment
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/rob/.julia/conda/3/envs/stan_dev

  added / updated specs:
    - cmdstan


The following NEW packages will be INSTALLED:

  cctools_osx-64     conda-forge/osx-64::cctools_osx-64-949.0.1-h6407bdd_23
  clang              conda-forge/osx-64::clang-11.1.0-h694c41f_1
  clang-11           conda-forge/osx-64::clang-11-11.1.0-default_he082bbe_1
  clang_osx-64       conda-forge/osx-64::clang_osx-64-11.1.0-hb91bd55_4
  clangxx            conda-forge/osx-64::clangxx-11.1.0-default_he082bbe_1
  clangxx_osx-64     conda-forge/osx-64::clangxx_osx-64-11.1.0-h7e1b574_4
  cmdstan            conda-forge/osx-64::cmdstan-2.28.2-h8783527_0
  compiler-rt        conda-forge/osx-64::compiler-rt-11.1.0-h654b07c_0
  compiler-rt_osx-64 conda-forge/noarch::compiler-rt_osx-64-11.1.0-h8c5fa43_0
  ld64_osx-64        conda-forge/osx-64::ld64_osx-64-530-he8994da_21
  ldid               conda-forge/osx-64::ldid-2.1.2-h6a69015_3
  libclang-cpp11.1   conda-forge/osx-64::libclang-cpp11.1-11.1.0-default_he082bbe_1
  libcxx             conda-forge/osx-64::libcxx-12.0.1-habf9029_0
  libllvm11          conda-forge/osx-64::libllvm11-11.1.0-hd011deb_2
  libllvm12          conda-forge/osx-64::libllvm12-12.0.1-hd011deb_2
  libzlib            conda-forge/osx-64::libzlib-1.2.11-h9173be1_1013
  llvm-tools         conda-forge/osx-64::llvm-tools-11.1.0-hd011deb_2
  make               conda-forge/osx-64::make-4.3-h22f3db7_1
  tapi               conda-forge/osx-64::tapi-1100.0.11-h9ce4665_0
  tbb                conda-forge/osx-64::tbb-2021.4.0-h940c156_1
  tbb-devel          conda-forge/osx-64::tbb-devel-2021.4.0-h940c156_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h9173be1_1013


Preparing transaction: done
Verifying transaction: done
Executing transaction: done

julia> StanBase.set_cmdstan_home!("/Users/rob/.julia/conda/3/env/stan_dev/bin/cmdstan")
"/Users/rob/.julia/conda/3/env/stan_dev/bin/cmdstan"

julia> CMDSTAN_HOME
"/Users/rob/.julia/conda/3/env/stan_dev/bin/cmdstan"

julia> include("/Users/rob/.julia/dev/StanSample/example/bernoulli.jl");
StanTable{Matrix{Float64}} with 2000 rows, 1 columns, and schema:
 :theta  Float64

julia> include("/Users/rob/.julia/dev/StanSample/example/bernoulli.jl");

/Users/rob/.julia/dev/StanSample/example/tmp/bernoulli.stan updated.
StanTable{Matrix{Float64}} with 2000 rows, 1 columns, and schema:
 :theta  Float64
```

This is on MacOS of course, but it might work on Windows.

**Comment by goedman** [comment]
I'll be out for a couple of hours, but get back to it.

**Comment by goedman** [comment]
Hi @jfb-h ,

Done a few more tests and it seems to work ok.

The one question I have is about the name of make, currently I use `make`, maybe on Windows that should be `mingw32_make`?

But interested what you are seeing.

Rob

**Comment by jfb-h** [comment]
Hi @goedman,

So before, I just used an existing anaconda install I had on my machine but I removed it this time around and also went through Conda.jl. Interesting that you managed to install with only `Conda.add("cmdstan", :stan_dev)`, I needed to throw in the channel with `Conda.add("cmdstan", :stan_dev, channel="conda-forge")` to get it to install.

My cmdstan home folder then was in `"C:\\Users\\Jakob\\.julia\\conda\\3\\envs\\stan_dev\\Library\\bin\\cmdstan"`, so I set `JULIA_CMDSTAN_HOME` and `CMDSTAN_HOME` accordingly. Btw., could you explain what the difference between the two is?

Trying the example model, I ran into a different issue this time around; Apparently, removing my existing Anaconda installation also removed g++ and mingw32-make and they haven't been installed again when installing cmdstan with Conda.jl. I'll try to investigate some more.

**Comment by jfb-h** [comment]
Ok so I found `C:\Users\Jakob\.julia\conda\3\envs\stan_dev\Library\mingw-w64\bin` which contains `g++.exe` and `mingw32-make.exe`, among others, and added it to the path.

However, when I try to compile the example model I now get the following error:

```julia
julia> sm = SampleModel("bernoulli", bernoulli_model, mktempdir())

C:\Users\Jakob\AppData\Local\Temp\jl_a7fDd1\bernoulli.stan updated.
ERROR:
Error when compiling SampleModel bernoulli:
INFO: Could not find files for the given pattern(s).
In file included from stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Core:96:0,
                 from stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:19,
                 from stan/src/stan/model/model_header.hpp:4,
                 from C:/Users/Jakob/AppData/Local/Temp/jl_a7fDd1/bernoulli.hpp:3:
C:/Users/Jakob/.julia/conda/3/envs/stan_dev/Library/mingw-w64/include/c++/5.3.0/complex:795:5: internal compiler error: Segmentation fault
     { return std::log(__z) / log(_Tp(10.0)); }
     ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
make: *** [make/program:58: C:\Users\Jakob\AppData\Local\Temp\jl_a7fDd1\bernoulli.exe] Error 1

Stacktrace:
 [1] SampleModel(name::String, model::String, tmpdir::String)
   @ StanSample C:\Users\Jakob\.julia\packages\StanSample\wyxSP\src\stanmodel\SampleModel.jl:105
 [2] top-level scope
   @ REPL[5]:1
```

**Comment by goedman** [comment]
Hi @jfb-h 

Apologies, it has been confusing I mixed a couple of objectives on my side (figuring out what is the problem on your system and learning the conda route to install cmdstan on Intel and M1 machines).

You should never have to touch CMDSTAN_HOME. As long as before you load StanSample.jl (`using StanSample`), the environment variable "JULIA_CMDSTAN_HOME" should point to the correct  cmdstan directory. At some point I added the "JULIA_" part to help in debugging issues as now `versioning()` will immediately show its value. 

If I had done my tests on my M1 machine (full conda is not supported on that processor, only conda-forge) I also would have added the channel.


I think the best way to move forward is to get back to situation where the cmdstan installation tests run fine (as you had when we started). I think the fact that you had to add parts to your path variable probably means it also won't be able to find libraries.

So in principle, a sequence such as:
```
(stan-env) rob@Rob-16-MBP bernoulli % conda list cmdstan
# packages in environment at /Users/rob/opt/miniconda3/envs/stan-env:
#
# Name                    Version                   Build  Channel
cmdstan                   2.28.2               h8783527_0    conda-forge

(stan-env) rob@Rob-16-MBP bernoulli % echo $JULIA_CMDSTAN_HOME                      
/Users/rob/.julia/conda/3/envs/stan_dev/bin/cmdstan

(stan-env) rob@Rob-16-MBP bernoulli % cd $JULIA_CMDSTAN_HOME
(stan-env) rob@Rob-16-MBP cmdstan % pwd
/Users/rob/.julia/conda/3/envs/stan_dev/bin/cmdstan

(stan-env) rob@Rob-16-MBP cmdstan % make examples/bernoulli/bernoulli               
make: 'examples/bernoulli/bernoulli' is up to date.


(stan-env) rob@Rob-16-MBP cmdstan % cd examples/bernoulli      
                     
(stan-env) rob@Rob-16-MBP bernoulli % ./bernoulli sample data file=bernoulli.data.json
method = sample (Default)
  sample
    num_samples = 1000 (Default)
    num_warmup = 1000 (Default)
    save_warmup = 0 (Default)
    thin = 1 (Default)
    adapt
      engaged = 1 (Default)
      gamma = 0.050000000000000003 (Default)
      delta = 0.80000000000000004 (Default)
      kappa = 0.75 (Default)
      t0 = 10 (Default)
      init_buffer = 75 (Default)
      term_buffer = 50 (Default)
      window = 25 (Default)
    algorithm = hmc (Default)
      hmc
        engine = nuts (Default)
          nuts
            max_depth = 10 (Default)
        metric = diag_e (Default)
        metric_file =  (Default)
        stepsize = 1 (Default)
        stepsize_jitter = 0 (Default)
    num_chains = 1 (Default)
id = 1 (Default)
data
  file = bernoulli.data.json
init = 2 (Default)
random
  seed = 2276584089 (Default)
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)
  sig_figs = -1 (Default)
  profile_file = profile.csv (Default)
num_threads = 1 (Default)


Gradient evaluation took 8e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.08 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  100 / 2000 [  5%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  300 / 2000 [ 15%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  700 / 2000 [ 35%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration:  900 / 2000 [ 45%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1100 / 2000 [ 55%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1300 / 2000 [ 65%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1500 / 2000 [ 75%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1700 / 2000 [ 85%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 1900 / 2000 [ 95%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.005 seconds (Warm-up)
               0.012 seconds (Sampling)
               0.017 seconds (Total)
```
as you had initially.

**Comment by jfb-h** [comment]
Hi Rob, 

no problem at all, I am definitely out of my depth here myself. Thanks again for your continued help!

I now created a completely new conda environment and removed the old ones and also removed the manual path entry to g++ etc. again and installed cmdstan into the new environment.

In the activated new conda env, I then am again able to compile the example model via the commandline from the cmdstan home directory. Also, from the activated conda environment I can check g++ and make versions. However, when I deactivate the conda env, g++ and make are no longer found.
I think probably related to this, I now get an error about g++ not being found when trying to use StanSample:

```julia
julia> ENV["JULIA_CMDSTAN_HOME"] = "C:\\Users\\Jakob\\.julia\\conda\\3\\envs\\stan-env\\Library\\bin\\cmdstan"
"C:\\Users\\Jakob\\.julia\\conda\\3\\envs\\stan-env\\Library\\bin\\cmdstan"

julia> using StanSample

julia> model = "
	  data { 
	    int<lower=0> N; 
	    int<lower=0,upper=1> y[N];
	  } 
	  parameters {
	    real<lower=0,upper=1> theta;
	  } 
	  model {
	    theta ~ beta(1,1);
	      y ~ bernoulli(theta);
	  }
  ";

julia> sm = SampleModel("bernoulli", model, mktempdir())
C:\Users\Jakob\AppData\Local\Temp\jl_4HWyhW\bernoulli.stan updated.
ERROR:
Error when compiling SampleModel bernoulli:
expr: syntax error: unexpected argument 'g++:'
sh: g++: command not found
INFO: Could not find files for the given pattern(s).
make: g++: Command not found
make: *** [make/program:58: C:\Users\Jakob\AppData\Local\Temp\jl_4HWyhW\bernoulli.exe] Error 127

Stacktrace:
 [1] SampleModel(name::String, model::String, tmpdir::String)
   @ StanSample C:\Users\Jakob\.julia\packages\StanSample\wyxSP\src\stanmodel\SampleModel.jl:105
 [2] top-level scope
```

**Comment by jfb-h** [comment]
Ah my bad, when I start the julia session in the correct activated conda env, g++ etc. are found but I am back to the original error message:

```julia
julia> sm = SampleModel("bernoulli", model, mktempdir())

C:\Users\Jakob\AppData\Local\Temp\jl_2sBRAI\bernoulli.stan updated.
ERROR:
Error when compiling SampleModel bernoulli:
/usr/bin/expr: missing operand
Try '/usr/bin/expr --help' for more information.
/usr/bin/rm: missing operand
Try '/usr/bin/rm --help' for more information.
make: *** [make/program:60: C:\Users\Jakob\AppData\Local\Temp\jl_2sBRAI\bernoulli.exe] Error 1

Stacktrace:
 [1] SampleModel(name::String, model::String, tmpdir::String)
   @ StanSample C:\Users\Jakob\.julia\packages\StanSample\wyxSP\src\stanmodel\SampleModel.jl:105
 [2] top-level scope
   @ REPL[4]:1
```

**Comment by jfb-h** [comment]
I see that in `SampleModel.jl:100` you call make directly:
```julia
success(pipeline(`make -f $(cmdstan_home)/makefile -C $(cmdstan_home) $(exec_path)`;
```
Does this maybe need to be `mingw32-make` on windows?

**Comment by jfb-h** [comment]
Hey wow that actually did it! I changed `make` to `mingw32-make` and were able to compile the model and draw samples etc.

**Comment by goedman** [comment]
Yes, that's a very real possibility. I will be back at my computer in about 2 hours and look at the code.

**Comment by goedman** [comment]
You could just update that line and try it.

**Comment by goedman** [comment]
That is great news!

I'll fix that in both StanBase.jl and StanSample.jl, should be merged later today.

It would be a great help if you could send me a step-by-step summary how you installed on Windows.

In any case, thanks for sticking with this issue!

Rob

**Comment by goedman** [comment]
Hi @jfb-h 

Both StanBase.jl (now v3.1.1) and StanBase.jl (now v5.1.1) have been merged and published.

That should work out of the box.

Rob

**Comment by jfb-h** [comment]
Great, thanks a lot! I'm away over the weekend but will check out the release on Monday and put together my installation steps.

**Comment by goedman** [comment]
All StanJulia packages have now been updated. At the same time I allowed the environment variable name that points to the cmdstan directory to be either CMDSTAN or JULIA_CMDSTAN_HOME. The new option, CMDSTAN, has been added because that what R and Python look for.

As far as installation steps are concerned, I'm particularly interested in deviations/additions from the Stan installation docs on using conda to install cmdstan. This route looks way simpler for Windows.

**Comment by jfb-h** [comment]
Hi @goedman,

currently precompilation for StanSample fails because of a typo in StanBase for which I created a PR.

For the installation walkthrough, here's my steps. I'll check if everything works in the end as soon as StanBase is fixed.


# Installation waklthrough for running Stan from Julia on Windows

1. Make sure you have conda installed on your system and available from the command line (you can use the conda version that comes with Conda.jl or install your own).

2. Activate the conda environment into which you want to install cmdstan (e.g. run `conda activate stan-env` from the command line) or create a new environment (`conda create --name stan-env`) and then activate it.

3. Install cmdstan into the active conda environment by running `conda install -c conda-forge cmdstan`.

4. You can check that cmdstan, g++, and mingw32-make are installed properly by running `conda list cmdstan`, `g++ --version` and `mingw32-make --version`, respectively, from the activated conda environment.

5. Start a Julia session from the conda environment in which cmdstan has been installed (this is necessary for the cmdstan installation and the tools to be found).

6. Add the `StanSample.jl` package by running `] add StanSample` from the REPL.

7. Set the `CMDSTAN` environment variable so that Julia can find the cmdstan installation, e.g. from the Julia REPL do: `ENV["CMDSTAN"] = "C:/Users/Jakob/.julia/conda/3/envs/stan-env/Library/bin/cmdstan"` This needs to be set before you load the `StanSample` package by e.g. `using` it. You can add this line to your `startup.jl` file so that you don't have to run it again in every fresh Julia session.

**Comment by jfb-h** [comment]
Thanks, happy I could be of help!

One last think I noticed: currently it is not enough to add `ENV["CMDSTAN"]` but I still had to specify `ENV["JULIA_CMDSTAN_HOME"]`. 

Otherwise, everything went smoothly now.

**Comment by goedman** [comment]
Hi @jfb-h 

Do you know where it failed if JULIA_CMDSTAN_HOME is not present? Did it compile when defining a SampleModel?

Weird, because on Github CI I do not define JULIA_CMDSTAN_HOME any longer (I think).

**Comment by jfb-h** [comment]
Hm weird, the problem occurs when I try to define the SampleModel:

```julia
julia> sm = SampleModel("bernoulli", model)

C:\Users\Jakob\AppData\Local\Temp\jl_Ii5M0r\bernoulli.stan updated.
ERROR: The environment variable JULIA_CMDSTAN_HOME needs to be set.
Stacktrace:
 [1] (::StanBase.var"#1#2")()
   @ StanBase C:\Users\Jakob\.julia\packages\StanBase\Zq7cr\src\common\cmdstan_home.jl:20
 [2] (::Base.var"#625#626"{StanBase.var"#1#2"})(k::String)
   @ Base .\env.jl:81
 [3] access_env(onError::Base.var"#625#626"{StanBase.var"#1#2"}, str::String)
   @ Base .\env.jl:14
 [4] get
   @ .\env.jl:81 [inlined]
 [5] get_cmdstan_home
   @ C:\Users\Jakob\.julia\packages\StanBase\Zq7cr\src\common\cmdstan_home.jl:19 [inlined]
 [6] SampleModel(name::String, model::String, tmpdir::String)
   @ StanSample C:\Users\Jakob\.julia\packages\StanSample\EP2ib\src\stanmodel\SampleModel.jl:96
 [7] SampleModel(name::String, model::String)
   @ StanSample C:\Users\Jakob\.julia\packages\StanSample\EP2ib\src\stanmodel\SampleModel.jl:90
 [8] top-level scope
   @ REPL[6]:1
```

**Comment by jfb-h** [comment]
Everything works smoothly now, thanks a lot!
