### ISSUE TITLE
Example Bernoulli not working under Julia 1.7.1

### ISSUE THREAD

**Issue by PToTheK** [StanJulia/StanSample.jl#49]
Dear Mr. Goedman,

It seems that the current example `bernoulli.jl` is not working under Julia Version 1.7.1.

The error message in the log-file is:

> num_chains=1 is either mistyped or misplaced.
> Failed to parse arguments, terminating Stan

Best regards,
Philipp

**Comment by goedman** [comment]
Hi Philip,

Looks like this is part of a message coming from cmdstan itself. I expect (but can’t be 100% sure) that your using
mismatched versions of StanSample.jl and the cmdstan executable.

Which version of StanSample are you using? StanSample v6.3.0 expects cmdstan-2.28.2 or cmdstan-2.29.0.

Do you mind checking which versions you have installed. With the introduction of support for C++ level threads in cmdstan-2.28.x and up I needed to make several updates to to StanSample.jl.

Best,
Rob


Rob J Goedman
***@***.***

**Comment by PToTheK** [comment]
Hi Rob,

Very good guess!
I use the newest version StanSample `StanSample v6.3.0,  but It seems I am using still `cmdstan-2.26.1`.

I will load the new version and report asap if that resolved the issue.

Thank you very much, for your qualified response.

**Comment by goedman** [comment]
Hi PToTheK,

Github remains down for me, so I’m using the mail side.

Simultaneously I’m helping someone else and I’m wondering if I can create a StanSample version that does not insert the `num_chains=1` argument if using Julia level “threads” (spawning a process for each chain).
If that would work on cmdstan versions < cmdstan-2.28.0 it might help many folks make the transition to newer versions. At least temporarily as the Stan Language itself is also changing a bit.

Best,
Rob

Rob J Goedman
***@***.***

**Comment by goedman** [comment]
Hi @PToTheK ,

A new version of StanSample.jl (v6.3.1) just got merged which I believe will, by default, be compatible with older versions of the cmdstan as long as the keyword argument use_cpp_chains=false (in the stan_sample() call). That is the default and multiple chains will execute on Julia level ( a process for each chain).

**Comment by PToTheK** [comment]
Hi @goedman,

I loaded `cmdstan-2.29.0` and `StanSample v6.3.0` works correctly now!

> "A new version of StanSample.jl (v6.3.1)..."

That sounds good! Indeed, this will make the transition for many users much smoother.

Thank you very much!

**Comment by goedman** [comment]
Great, thanks for the update Philipp.
