### ISSUE TITLE
Set Integer eltypes of sampling statistics

### ISSUE THREAD

**Issue by sethaxen** [StanJulia/StanSample.jl#68]
I noticed that when using `inferencedata`, the `Integer` eltype variables in the `sample_stats` group have `Float64` eltypes. I suggest the following eltypes be used:
- `diverging` -> `Bool`
- `n_steps` -> `Int`
- `tree_depth` -> `Int`

I'm guessing this needs to happen upstream of `inferencedata`, perhaps in `read_samples`?

**Comment by goedman** [comment]
Thanks Seth, agreed that that should happen in read_samples. I'll take a look!

**Comment by goedman** [comment]
Hi Seth (@sethaxen), should be fixed in StanSample v7.0.1.

Currently I fixed it for NamedTuples and DataFrames.

**Comment by sethaxen** [comment]
Thanks! Seems to work well!
